### PR TITLE
Add mip_era particular processing to publish CMIP6 properly

### PR DESCRIPTION
**Pull request by glevava**
"project" is a particular facet for the publisher as for instance "model" or "experiment".
Because "mip_era" is intended to replace "project" for MIP project, the publisher needs to consider it in the same way as "project" but with a different label.

### CODE REVIEW

**Comment by glevava** [comment]
This allows to remove the "mip_era_options" from esg.cmip6.ini.

**Comment by sashakames** [comment]
testing in glevava-devel branch

**Comment by glevava** [comment]
Additional minor changes to cmip6 publication

**Comment by sashakames** [comment]
get this error with the publication test:    File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.3a0-py2.7.egg/esgcet/config/config.py", line 56, in get
    value = SafeConfigParser.get(self, section, option, raw=raw, vars=vars)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'config:test'

While we could put in a placeholder value in esg.ini (and I will to continue the test), I suspect this would be needed for every project and that doesn't seem like a good practice.

**Comment by soay** [comment]
I don't get that error, neither does Guillaume. Looking at Guillaume's modifications I don't think the pull request is the cause of the issue. Maybe you are using the cmip6 handler for the test ini file?

**Comment by sashakames** [comment]
this commit - https://github.com/glevava/esg-publisher/commit/37522e49aee6b1c52e2f79880af5dd666a1dfbb1#diff-f1c72a2ee6986356276891995897e54d - should fix it - perhaps that didn't propagate to my test so will try again

**Comment by sashakames** [comment]
Passed my esgtest_publish run!  onto CMIP6 testing with the updated data

**Pull request merged**
