### PR TITLE
a line to change in esg.ini

### PR DESCRIPTION
**Pull request by alaniwi**
THREDDS reinit response has changed; change string to search for, as reinit otherwise claims to have failed

### CODE REVIEW

**Comment by sashakames** [comment]
The 5.0.X THREDDS as deployed with ESGF v2.1 uses the "reinit ok" message, as that has been consistent in our test deployments.  Which version of THREDDS are you running?

**Comment by alaniwi** [comment]
In `/usr/local/tomcat/webapps/thredds/WEB-INF/classes/thredds/server/tds.properties`:

`tds.version=5.0.0-SNAPSHOT`

Also I have:
`thredds_reinit_url = https://localhost:443/thredds/admin/debug?Catalogs/recheck`

and I get:

```
esgcet.exceptions.ESGPublishError: Error reinitializing the THREDDS Data Server. Result='<!DOCTYPE html PUBLIC \'-//W3C//DTD HTML 4.01 Transitional//EN\'\n        \'http://www.w3.org/TR/html4/loose.dtd\'>\n<html>\n\n<head>\n<title> THREDDS Debug</title>\n<meta http-equiv="Content-Type" content="text/html">\n<link rel=\'stylesheet\' href=\'/thredds/tds.css\' type=\'text/css\' >\n</head>\n<body>\n<table width=\'100%\'>\n<tr><td>\n<img src=\'/thredds/threddsIcon.gif\' alt=\'Initial TDS Installation\' align=\'left\' valign=\'top\' hspace=\'10\' vspace=\'2\'>\n<h3><strong><a href=\'/thredds/catalog.html\'>Initial TDS Installation</a></strong></h3>\n<h3><strong><a href=\'http://www.unidata.ucar.edu/software/thredds/current/tds/TDS.html\'>THREDDS Data Server</a></strong></h3>\n</td></tr>\n</table>\n\n<br><a href=\'dir/content/thredds/logs/\'>Show TDS Logs</a>\n<br><a href=\'dir/content/tdm/\'>Show TDM Logs</a>\n<br><a href=\'dir/logs/\'>Show Tomcat Logs</a>\n<br><a href=\'dir/catalogs/\'>Show Config Catalogs</a>\n<br><a href=\'spring/showControllers\'>Show Spring Controllers</a>\n<h2>Debug Actions</h2>\n<pre>\nCmd= Catalogs/recheck\n<p/>Reading changed catalogs\n</pre></body></html>\n'
```

**Comment by alaniwi** [comment]
And for readability, here is that response string `print`-ed:

```
<!DOCTYPE html PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN'
        'http://www.w3.org/TR/html4/loose.dtd'>
<html>

<head>
<title> THREDDS Debug</title>
<meta http-equiv="Content-Type" content="text/html">
<link rel='stylesheet' href='/thredds/tds.css' type='text/css' >
</head>
<body>
<table width='100%'>
<tr><td>
<img src='/thredds/threddsIcon.gif' alt='Initial TDS Installation' align='left' valign='top' hspace='10' vspace='2'>
<h3><strong><a href='/thredds/catalog.html'>Initial TDS Installation</a></strong></h3>
<h3><strong><a href='http://www.unidata.ucar.edu/software/thredds/current/tds/TDS.html'>THREDDS Data Server</a></strong></h3>
</td></tr>
</table>

<br><a href='dir/content/thredds/logs/'>Show TDS Logs</a>
<br><a href='dir/content/tdm/'>Show TDM Logs</a>
<br><a href='dir/logs/'>Show Tomcat Logs</a>
<br><a href='dir/catalogs/'>Show Config Catalogs</a>
<br><a href='spring/showControllers'>Show Spring Controllers</a>
<h2>Debug Actions</h2>
<pre>
Cmd= Catalogs/recheck
<p/>Reading changed catalogs
</pre></body></html>
```

**Comment by alaniwi** [comment]
The problem is the URL.  At present the "recheck" URL is uncommented, but with a pattern appropriate to the "reinit" URL.  Please see additional commit above, which reorganises the comment lines to clarify things.  I am leaving the recheck URL uncommented because it seems to work, and is a lot faster.

**Comment by sashakames** [comment]
Do you have a TDS build date?
I published to a test node with the following with the current esg.ini defaults.  There was an older THREDDS deployment where the output strings had differed but John C. has fixed this to report the same string.

tds.version.builddate=2015-12-03T07:59:46-0700

**Comment by alaniwi** [comment]
tds.version.builddate=2015-09-20T23:04:22-0600

**Comment by sashakames** [comment]
That version most likely predates John's change.  If you haven't reinstalled your test node since that data, there are probably plenty of additional changes worth picking up.

**Pull request closed without merging**
